# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField(default=0)),
                ('left_seats', models.IntegerField(default=0)),
                ('booked_seats', models.CharField(max_length=2000)),
                ('cover_logo', models.FileField(upload_to='')),
            ],
        ),
    ]
